### PR TITLE
Update snapd and secboot to support shim 15.8

### PR DESCRIPTION
**Pull request by kukrimate**

### CODE REVIEW

**Comment by gjolly** [comment]
@kukrimate can you please edit the commit message to describe why this change is needed with the new shim?

**Comment by kukrimate** [comment]
@gjolly done

**Comment by gjolly** [comment]
This was tested locally by encrypting and deploying 2 VM images: one including `nullboot` `0.5.1-0ubuntu1` (with `shim` `15.8`) and another including `nullboot` `0.5.0-0ubuntu3` (with `shim` `15.7`). We verified we could successfully boot those 2 images.

**Review by gjolly — APPROVED** [review]

**Review by chrisccoulson — APPROVED** [review]
This looks ok to me. The long term fix would be to get this and nullboot (and snapd) using https://github.com/snapcore/secboot/blob/427c0f7451ab9177d72ecf8a87b5e7923ec7e998/efi/pcr_profile.go#L153 which handles this correctly and contains quirks for known bugs so we can hopefully avoid having to keep doing this.

**Comment by chrisccoulson** [comment]
> This looks ok to me. The long term fix would be to get this and nullboot (and snapd) using https://github.com/snapcore/secboot/blob/427c0f7451ab9177d72ecf8a87b5e7923ec7e998/efi/pcr_profile.go#L153 which handles this correctly and contains quirks for known bugs so we can hopefully avoid having to keep doing this.

And also to get secboot using https://pkg.go.dev/github.com/canonical/go-tpm2@master/policyutil#PolicyBuilder so that we have policy structures stored in key slots which will make this stuff much easier to debug (by just doing `fmt.Print(policy)` to see what a policy looks like)

**Comment by kukrimate** [comment]
Yeah, this whole thing is definitely not nice, this is only to un-break Noble CVM images for now. We should fix this properly for sure.

**Pull request merged**
